### ISSUE TITLE
LavaPlayer not working properly when relocating

### ISSUE THREAD

**Issue by BaxAndrei** [devoxin/lavaplayer#18]
I am getting this error when lavaplayer try to play some mp3: `Something went wrong when looking up the track` and this error when it try to play ogg files:
```
Exception in thread "lava-daemon-pool-playback-1-thread-1" java.lang.UnsatisfiedLinkError: 'long ro.baxandrei.discordbot.lib.lavaplayer.natives.opus.OpusDecoderLibrary.create(int, int)'
        at ro.baxandrei.discordbot.lib.lavaplayer.natives.opus.OpusDecoderLibrary.create(Native Method)
        at ro.baxandrei.discordbot.lib.lavaplayer.natives.opus.OpusDecoder.<init>(OpusDecoder.java:21)
        at ro.baxandrei.discordbot.lib.lavaplayer.container.common.OpusPacketRouter.initialiseDecoder(OpusPacketRouter.java:193)
        at ro.baxandrei.discordbot.lib.lavaplayer.container.common.OpusPacketRouter.checkDecoderNecessity(OpusPacketRouter.java:177)
        at ro.baxandrei.discordbot.lib.lavaplayer.container.common.OpusPacketRouter.process(OpusPacketRouter.java:93)
        at ro.baxandrei.discordbot.lib.lavaplayer.container.ogg.opus.OggOpusTrackHandler.provideFrames(OggOpusTrackHandler.java:51)
        at ro.baxandrei.discordbot.lib.lavaplayer.container.ogg.OggAudioTrack.processTrackLoop(OggAudioTrack.java:58)
        at ro.baxandrei.discordbot.lib.lavaplayer.container.ogg.OggAudioTrack.lambda$process$0(OggAudioTrack.java:41)
        at ro.baxandrei.discordbot.lib.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:275)
        at ro.baxandrei.discordbot.lib.lavaplayer.container.ogg.OggAudioTrack.process(OggAudioTrack.java:39)
        at ro.baxandrei.discordbot.lib.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
        at ro.baxandrei.discordbot.lib.lavaplayer.source.local.LocalAudioTrack.process(LocalAudioTrack.java:45)
        at ro.baxandrei.discordbot.lib.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104)
        at ro.baxandrei.discordbot.lib.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

After many hours of try/fail I reached a result: if I delete relocation for com.sedmelluq.discord.lavaplayer.natives everything works ok.

How could I relocate this package without breaking lavaplayer?

Thank you!

**Comment by devoxin** [comment]
I am not sure what you're asking. Are you running Lavaplayer on a supported platform/architecture?

**Comment by BaxAndrei** [comment]
Yes. Everything works perfectly, but if I add this line in pom.xml to relocate the package, it doesn't work anymore. (I add the line for personal reasons)

```
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>${maven.shade.plugin.version}</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                            </transformers>
                            <minimizeJar>true</minimizeJar>
                            <relocations>
                               .....
                                <relocation>
                                    <pattern>com.sedmelluq.discord.lavaplayer</pattern>
                                    <shadedPattern>ro.baxandrei.discordbot.lib.lavaplayer</shadedPattern>
                                </relocation>
                                ........
                            </relocations>
                            <createDependencyReducedPom>true</createDependencyReducedPom>
                            <filters>
                                ....
                            </filters>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

**Comment by devoxin** [comment]
Yes because natives work based on package path. That package path is `com.sedmelluq.*` so renaming it won't work. What you are trying to do is unsupported.

**Comment by BaxAndrei** [comment]
> Yes because natives work based on package path. That package path is `com.sedmelluq.*` so renaming it won't work. What you are trying to do is unsupported.

Do you think you could please show me where these values ​​are hardcoded so that I can modify them manually and make my own version? Thank you.

EDIT: Also relocation is smart enough to remap all package paths but there must be something hardcoded or stored as string/text
![image](https://github.com/user-attachments/assets/19cf8822-a702-41c2-99fc-44d1a6feb3e5)

**Comment by devoxin** [comment]
It's within the **compiled** natives themselves. Not only would you need to modify the natives source but you would need to figure out how to compile them. This is not something I offer support for due to how arduous and temperamental the build process is.

**Comment by BaxAndrei** [comment]
> It's within the **compiled** natives themselves. Not only would you need to modify the natives source but you would need to figure out how to compile them. This is not something I offer support for due to how arduous and temperamental the build process is.

I understand now, thank you very much for the answer. I will figure out a solution now that you said this. Have a nice day.
